//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aggregationCalculationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="aggregationCalculationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Nothing"/&gt;
 *     &lt;enumeration value="Count"/&gt;
 *     &lt;enumeration value="DistinctCount"/&gt;
 *     &lt;enumeration value="Sum"/&gt;
 *     &lt;enumeration value="Average"/&gt;
 *     &lt;enumeration value="Lowest"/&gt;
 *     &lt;enumeration value="Highest"/&gt;
 *     &lt;enumeration value="StandardDeviation"/&gt;
 *     &lt;enumeration value="Variance"/&gt;
 *     &lt;enumeration value="First"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "aggregationCalculationType")
@XmlEnum
public enum AggregationCalculationType {


    /**
     * No calculations are performed.
     * 
     */
    @XmlEnumValue("Nothing")
    NOTHING("Nothing"),

    /**
     * The measure stores the number of the not null
     *       values.
     * 
     */
    @XmlEnumValue("Count")
    COUNT("Count"),

    /**
     * The measure stores the number of distinct not null
     *       values.
     * 
     */
    @XmlEnumValue("DistinctCount")
    DISTINCT_COUNT("DistinctCount"),

    /**
     * The measure stores the sum of the not null values.
     *       Numeric measures only.
     * 
     */
    @XmlEnumValue("Sum")
    SUM("Sum"),

    /**
     * The measure stores the average of the not null
     *       values. Numeric measures only.
     * 
     */
    @XmlEnumValue("Average")
    AVERAGE("Average"),

    /**
     * The measure stores the lowest value.
     * 
     */
    @XmlEnumValue("Lowest")
    LOWEST("Lowest"),

    /**
     * The measure stores the highest value.
     *      
     * 
     */
    @XmlEnumValue("Highest")
    HIGHEST("Highest"),

    /**
     * The measure stores the standard deviation of the not
     *       null values. Numeric measures only.
     * 
     */
    @XmlEnumValue("StandardDeviation")
    STANDARD_DEVIATION("StandardDeviation"),

    /**
     * The measure stores the variance of the not null
     *       values. Numeric measures only.
     * 
     */
    @XmlEnumValue("Variance")
    VARIANCE("Variance"),

    /**
     * The measure stores the first value encountered and
     *       ignores subsequent values.
     * 
     */
    @XmlEnumValue("First")
    FIRST("First");
    private final String value;

    AggregationCalculationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AggregationCalculationType fromValue(String v) {
        for (AggregationCalculationType c: AggregationCalculationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
