//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}labelFont" minOccurs="0"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}tickLabelFont" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="labelColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tickLabelColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tickLabelMask" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="verticalTickLabels" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="axisLineColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "labelFont",
    "tickLabelFont"
})
@XmlRootElement(name = "axisFormat")
public class AxisFormat {

    protected LabelFont labelFont;
    protected TickLabelFont tickLabelFont;
    @XmlAttribute(name = "labelColor")
    protected String labelColor;
    @XmlAttribute(name = "tickLabelColor")
    protected String tickLabelColor;
    @XmlAttribute(name = "tickLabelMask")
    protected String tickLabelMask;
    @XmlAttribute(name = "verticalTickLabels")
    protected Boolean verticalTickLabels;
    @XmlAttribute(name = "axisLineColor")
    protected String axisLineColor;

    /**
     * Gets the value of the labelFont property.
     * 
     * @return
     *     possible object is
     *     {@link LabelFont }
     *     
     */
    public LabelFont getLabelFont() {
        return labelFont;
    }

    /**
     * Sets the value of the labelFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelFont }
     *     
     */
    public void setLabelFont(LabelFont value) {
        this.labelFont = value;
    }

    /**
     * Gets the value of the tickLabelFont property.
     * 
     * @return
     *     possible object is
     *     {@link TickLabelFont }
     *     
     */
    public TickLabelFont getTickLabelFont() {
        return tickLabelFont;
    }

    /**
     * Sets the value of the tickLabelFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link TickLabelFont }
     *     
     */
    public void setTickLabelFont(TickLabelFont value) {
        this.tickLabelFont = value;
    }

    /**
     * Gets the value of the labelColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelColor() {
        return labelColor;
    }

    /**
     * Sets the value of the labelColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelColor(String value) {
        this.labelColor = value;
    }

    /**
     * Gets the value of the tickLabelColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTickLabelColor() {
        return tickLabelColor;
    }

    /**
     * Sets the value of the tickLabelColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTickLabelColor(String value) {
        this.tickLabelColor = value;
    }

    /**
     * Gets the value of the tickLabelMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTickLabelMask() {
        return tickLabelMask;
    }

    /**
     * Sets the value of the tickLabelMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTickLabelMask(String value) {
        this.tickLabelMask = value;
    }

    /**
     * Gets the value of the verticalTickLabels property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerticalTickLabels() {
        return verticalTickLabels;
    }

    /**
     * Sets the value of the verticalTickLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerticalTickLabels(Boolean value) {
        this.verticalTickLabels = value;
    }

    /**
     * Gets the value of the axisLineColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxisLineColor() {
        return axisLineColor;
    }

    /**
     * Sets the value of the axisLineColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxisLineColor(String value) {
        this.axisLineColor = value;
    }

}
