//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for basicEvaluationTime.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="basicEvaluationTime"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Now"/&gt;
 *     &lt;enumeration value="Report"/&gt;
 *     &lt;enumeration value="Page"/&gt;
 *     &lt;enumeration value="Column"/&gt;
 *     &lt;enumeration value="Group"/&gt;
 *     &lt;enumeration value="Band"/&gt;
 *     &lt;enumeration value="Master"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "basicEvaluationTime")
@XmlEnum
public enum BasicEvaluationTime {

    @XmlEnumValue("Now")
    NOW("Now"),
    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("Page")
    PAGE("Page"),
    @XmlEnumValue("Column")
    COLUMN("Column"),
    @XmlEnumValue("Group")
    GROUP("Group"),
    @XmlEnumValue("Band")
    BAND("Band"),
    @XmlEnumValue("Master")
    MASTER("Master");
    private final String value;

    BasicEvaluationTime(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BasicEvaluationTime fromValue(String v) {
        for (BasicEvaluationTime c: BasicEvaluationTime.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
