//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}chart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}xyzDataset"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}bubblePlot"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chart",
    "xyzDataset",
    "bubblePlot"
})
@XmlRootElement(name = "bubbleChart")
public class BubbleChart {

    @XmlElement(required = true)
    protected Chart chart;
    @XmlElement(required = true)
    protected XyzDataset xyzDataset;
    @XmlElement(required = true)
    protected BubblePlot bubblePlot;

    /**
     * Gets the value of the chart property.
     * 
     * @return
     *     possible object is
     *     {@link Chart }
     *     
     */
    public Chart getChart() {
        return chart;
    }

    /**
     * Sets the value of the chart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chart }
     *     
     */
    public void setChart(Chart value) {
        this.chart = value;
    }

    /**
     * Gets the value of the xyzDataset property.
     * 
     * @return
     *     possible object is
     *     {@link XyzDataset }
     *     
     */
    public XyzDataset getXyzDataset() {
        return xyzDataset;
    }

    /**
     * Sets the value of the xyzDataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link XyzDataset }
     *     
     */
    public void setXyzDataset(XyzDataset value) {
        this.xyzDataset = value;
    }

    /**
     * Gets the value of the bubblePlot property.
     * 
     * @return
     *     possible object is
     *     {@link BubblePlot }
     *     
     */
    public BubblePlot getBubblePlot() {
        return bubblePlot;
    }

    /**
     * Sets the value of the bubblePlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BubblePlot }
     *     
     */
    public void setBubblePlot(BubblePlot value) {
        this.bubblePlot = value;
    }

}
