//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}lowExpression"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}highExpression"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lowExpression",
    "highExpression"
})
@XmlRootElement(name = "dataRange")
public class DataRange {

    @XmlElement(required = true)
    protected LowExpression lowExpression;
    @XmlElement(required = true)
    protected HighExpression highExpression;

    /**
     * Gets the value of the lowExpression property.
     * 
     * @return
     *     possible object is
     *     {@link LowExpression }
     *     
     */
    public LowExpression getLowExpression() {
        return lowExpression;
    }

    /**
     * Sets the value of the lowExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowExpression }
     *     
     */
    public void setLowExpression(LowExpression value) {
        this.lowExpression = value;
    }

    /**
     * Gets the value of the highExpression property.
     * 
     * @return
     *     possible object is
     *     {@link HighExpression }
     *     
     */
    public HighExpression getHighExpression() {
        return highExpression;
    }

    /**
     * Sets the value of the highExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighExpression }
     *     
     */
    public void setHighExpression(HighExpression value) {
        this.highExpression = value;
    }

}
