//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}break"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}line"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}rectangle"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}ellipse"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}image"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}staticText"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}textField"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}subreport"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}pieChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}pie3DChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}barChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}bar3DChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}xyBarChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}stackedBarChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}stackedBar3DChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}lineChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}xyLineChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}areaChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}xyAreaChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}scatterChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}bubbleChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}timeSeriesChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}highLowChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}candlestickChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}meterChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}thermometerChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}multiAxisChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}stackedAreaChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}ganttChart"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}elementGroup"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}crosstab"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}frame"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}componentElement"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}genericElement"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "breakOrLineOrRectangle"
})
@XmlRootElement(name = "elementGroup")
public class ElementGroup {

    @XmlElements({
        @XmlElement(name = "break", type = Break.class),
        @XmlElement(name = "line", type = Line.class),
        @XmlElement(name = "rectangle", type = Rectangle.class),
        @XmlElement(name = "ellipse", type = Ellipse.class),
        @XmlElement(name = "image", type = Image.class),
        @XmlElement(name = "staticText", type = StaticText.class),
        @XmlElement(name = "textField", type = TextField.class),
        @XmlElement(name = "subreport", type = Subreport.class),
        @XmlElement(name = "pieChart", type = PieChart.class),
        @XmlElement(name = "pie3DChart", type = Pie3DChart.class),
        @XmlElement(name = "barChart", type = BarChart.class),
        @XmlElement(name = "bar3DChart", type = Bar3DChart.class),
        @XmlElement(name = "xyBarChart", type = XyBarChart.class),
        @XmlElement(name = "stackedBarChart", type = StackedBarChart.class),
        @XmlElement(name = "stackedBar3DChart", type = StackedBar3DChart.class),
        @XmlElement(name = "lineChart", type = LineChart.class),
        @XmlElement(name = "xyLineChart", type = XyLineChart.class),
        @XmlElement(name = "areaChart", type = AreaChart.class),
        @XmlElement(name = "xyAreaChart", type = XyAreaChart.class),
        @XmlElement(name = "scatterChart", type = ScatterChart.class),
        @XmlElement(name = "bubbleChart", type = BubbleChart.class),
        @XmlElement(name = "timeSeriesChart", type = TimeSeriesChart.class),
        @XmlElement(name = "highLowChart", type = HighLowChart.class),
        @XmlElement(name = "candlestickChart", type = CandlestickChart.class),
        @XmlElement(name = "meterChart", type = MeterChart.class),
        @XmlElement(name = "thermometerChart", type = ThermometerChart.class),
        @XmlElement(name = "multiAxisChart", type = MultiAxisChart.class),
        @XmlElement(name = "stackedAreaChart", type = StackedAreaChart.class),
        @XmlElement(name = "ganttChart", type = GanttChart.class),
        @XmlElement(name = "elementGroup", type = ElementGroup.class),
        @XmlElement(name = "crosstab", type = Crosstab.class),
        @XmlElement(name = "frame", type = Frame.class),
        @XmlElement(name = "componentElement", type = ComponentElement.class),
        @XmlElement(name = "genericElement", type = GenericElement.class)
    })
    protected List<Object> breakOrLineOrRectangle;

    /**
     * Gets the value of the breakOrLineOrRectangle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the breakOrLineOrRectangle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBreakOrLineOrRectangle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AreaChart }
     * {@link Bar3DChart }
     * {@link BarChart }
     * {@link Break }
     * {@link BubbleChart }
     * {@link CandlestickChart }
     * {@link ComponentElement }
     * {@link Crosstab }
     * {@link ElementGroup }
     * {@link Ellipse }
     * {@link Frame }
     * {@link GanttChart }
     * {@link GenericElement }
     * {@link HighLowChart }
     * {@link Image }
     * {@link Line }
     * {@link LineChart }
     * {@link MeterChart }
     * {@link MultiAxisChart }
     * {@link Pie3DChart }
     * {@link PieChart }
     * {@link Rectangle }
     * {@link ScatterChart }
     * {@link StackedAreaChart }
     * {@link StackedBar3DChart }
     * {@link StackedBarChart }
     * {@link StaticText }
     * {@link Subreport }
     * {@link TextField }
     * {@link ThermometerChart }
     * {@link TimeSeriesChart }
     * {@link XyAreaChart }
     * {@link XyBarChart }
     * {@link XyLineChart }
     * 
     * 
     */
    public List<Object> getBreakOrLineOrRectangle() {
        if (breakOrLineOrRectangle == null) {
            breakOrLineOrRectangle = new ArrayList<Object>();
        }
        return this.breakOrLineOrRectangle;
    }

}
