//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}multiAxisDataset"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}dataAxis" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}multiAxisMeasure" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "multiAxisDataset",
    "dataAxis",
    "multiAxisMeasure"
})
@XmlRootElement(name = "multiAxisData")
public class MultiAxisData {

    @XmlElement(required = true)
    protected MultiAxisDataset multiAxisDataset;
    @XmlElement(required = true)
    protected List<DataAxis> dataAxis;
    @XmlElement(required = true)
    protected List<MultiAxisMeasure> multiAxisMeasure;

    /**
     * Gets the value of the multiAxisDataset property.
     * 
     * @return
     *     possible object is
     *     {@link MultiAxisDataset }
     *     
     */
    public MultiAxisDataset getMultiAxisDataset() {
        return multiAxisDataset;
    }

    /**
     * Sets the value of the multiAxisDataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiAxisDataset }
     *     
     */
    public void setMultiAxisDataset(MultiAxisDataset value) {
        this.multiAxisDataset = value;
    }

    /**
     * Gets the value of the dataAxis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataAxis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataAxis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataAxis }
     * 
     * 
     */
    public List<DataAxis> getDataAxis() {
        if (dataAxis == null) {
            dataAxis = new ArrayList<DataAxis>();
        }
        return this.dataAxis;
    }

    /**
     * Gets the value of the multiAxisMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiAxisMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiAxisMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiAxisMeasure }
     * 
     * 
     */
    public List<MultiAxisMeasure> getMultiAxisMeasure() {
        if (multiAxisMeasure == null) {
            multiAxisMeasure = new ArrayList<MultiAxisMeasure>();
        }
        return this.multiAxisMeasure;
    }

}
