//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://jasperreports.sourceforge.net/jasperreports", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.logof.xlsToJasper.jasper.report;
