//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://jasperreports.sourceforge.net/jasperreports}axisFormat"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "axisFormat"
})
@XmlRootElement(name = "timeAxisFormat")
public class TimeAxisFormat {

    @XmlElement(required = true)
    protected AxisFormat axisFormat;

    /**
     * Gets the value of the axisFormat property.
     * 
     * @return
     *     possible object is
     *     {@link AxisFormat }
     *     
     */
    public AxisFormat getAxisFormat() {
        return axisFormat;
    }

    /**
     * Sets the value of the axisFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxisFormat }
     *     
     */
    public void setAxisFormat(AxisFormat value) {
        this.axisFormat = value;
    }

}
