//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:38:23 PM YEKT 
//


package org.logof.xlsToJasper.jasper.report;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for variableReturnValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variableReturnValue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://jasperreports.sourceforge.net/jasperreports}commonReturnValue"&gt;
 *       &lt;attribute name="fromVariable" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variableReturnValue")
public class VariableReturnValue
    extends CommonReturnValue
{

    @XmlAttribute(name = "fromVariable")
    protected String fromVariable;

    /**
     * Gets the value of the fromVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromVariable() {
        return fromVariable;
    }

    /**
     * Sets the value of the fromVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromVariable(String value) {
        this.fromVariable = value;
    }

}
